apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:fPDjpS9E3bfk6rQHPnM=,iv:nlmI0azTmR1aXrEZGVg82tGvDKSDH9iU6ohfbpRU2Sk=,tag:YooOh9wkOl5Te9264w620A==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:Zwyez86HHVMou1OL,iv:8J31z9P3SFkLdcFK+O4HVySm6Mmz0jRspRu1xQbQl14=,tag:+6+SVPttr37tWP9Kl1aFqA==,type:str]
    CLUSTER_INGRESS_ADDR: ENC[AES256_GCM,data:JgWMaqWUoEMknUR5,iv:UwfkaFjM33N5PC4pgNvfHotBbh8JwV25rio5/9hTTlo=,tag:s4A2cOz8Lp/9ngYZl3QDyg==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:eyB4S5qtCtU=,iv:2ZSCxgPMPP5xLMbgZEg58/ouQQ291Tw2FAsctF/dq6c=,tag:cUj8BTGlsxAhRamCgt6pFQ==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ReALhgK3nUQBH5o1jvcrxIq9,iv:HIX012Vf4vld3wIq5e24sJJbrN09iRYaXc95LaEDK7Q=,tag:fSp/tMCuRsQA/eiFwRK97Q==,type:str]
    NZBGET_USER: ENC[AES256_GCM,data:R7h1gr4=,iv:QsZLCbxncLZW00vu87MCmPBGZG7UWnSQDusP4PzfnJE=,tag:mE5SUSOGyzcwx8I+1FI6ZQ==,type:str]
    NZBGET_PASSWORD: ENC[AES256_GCM,data:biJA9dkDW0HE,iv:/UC48NPppcCvY+n1QCH1LhmwzTr1nrwbwFffIZ6Fnzc=,tag:IZDPk4ZGGHRVXRlaFso5jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eERvTzEvaXRuSUJWOERG
            K2VncGhKNCtiTFFPM3ZmaXZZd3FHNm8wV1VnCjRabGFTYURUR2pZeEsxTGlrODNM
            ZDVxK0M2M1J2cVFWZ2w2SWZORng0MFUKLS0tIGFNSFFDeldDTERZWE5vSkVOYmcv
            bE92czBrdXdHSmFqajNGVlc2VTVTWVUKYh8PYjPL6rtytGbHp/AVSaIrkylqS2DK
            ta12aK3ez7UAsCzhtaA4ntxIqLpXvh2aLIXV/S+qZ9nj1f4stv/AIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-31T00:08:23Z"
    mac: ENC[AES256_GCM,data:u14bn7ole22FPYSuSaQOxTODKNAMtl0DAtBegv1xXgzMPHFncIzq+TG9ZCG65l2zRh3w+laH/hKpHDvMalUqWVjr4g1x+6kkYhBYJuwgdIidxVAIKl2L/GkcLfV6GwoOcld4juU8K+FK9AOiQK68QdTkuRyzBZI8GyjLadTQC8E=,iv:+RpslwhdtqIcZNv3mH9fCUYkd2kj5sZKnPcwAUkCI7I=,tag:8plSfB6X6I2s2tNeJVpGxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
