apiVersion: apps/v1
kind: Deployment
metadata:
  name: manga-scraper
  namespace: manga-scraper
  labels:
    app: manga-scraper
spec:
  selector:
    matchLabels:
      app: manga-scraper
  replicas: 1
  template:
    metadata:
      labels:
        app: manga-scraper
    spec:
      containers:
        - name: manga-scraper
          image: ghcr.io/davidharrigan/manga-scraper:0.0.2
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: MANGA_SCRAPER_DATABASE_URL
              value: ${MANGA_SCRAPER_DATABASE_URL}
            - name: MANGA_SCRAPER_SLACKTOKEN
              value: ${MANGA_SCRAPER_SLACK_TOKEN}
            - name: MANGA_SCRAPER_PORT
              value: "3000"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
