---
apiVersion: v1
kind: Service
metadata:
  name: manga-scraper
  namespace: manga-scraper
  labels:
    app: manga-scraper
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: manga-scraper
  type: ClusterIP
