---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.23.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1
    env:
      GF_EXPLORE_ENABLED: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
    adminPassword: "${GRAFANA_PASSWORD}"
    grafana.ini:
      server:
        root_url: "https://grafana.${DOMAIN}"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      auth.basic:
        disable_login_form: false
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-prometheus:9090/
            isDefault: true
          # - name: Loki
          #   type: loki
          #   access: proxy
          #   url: http://loki:3100
    # dashboards:
      # default:
        # Ref: https://grafana.com/grafana/dashboards/13978
        # node_exporter:
        #   gnetId: 13978
        #   revision: 1
        #   datasource: Prometheus

    sidecar:
      dashboards:
        enabled: true
        # label key that the ConfigMaps containing dashboards should have to be collected by the sidecar
        # The value is unused, the ConfigMap could be labelled as:
        # label:
        #   grafana_dashboard: "true"
        label: grafana_dashboard
        searchNamespace: ALL
        # If specified, the sidecar will look for annotation with this name to create folder and put graph here.
        # You can use this parameter together with `provider.foldersFromFilesStructure`to annotate configmaps and create folder structure.
        folderAnnotation: grafana_folder
        provider:
          allowUiUpdates: true
          foldersFromFilesStructure: true
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - vonage-status-panel
      - grafana-worldmap-panel
      - grafana-clock-panel
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "chart-areaspline"
        hajimari.io/appName: "Grafana"
      hosts:
        - &host "grafana.${DOMAIN}"
      tls:
        - hosts:
            - *host
    serviceAccount:
      create: true
      autoMount: true
    persistence:
      enabled: false