---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: proxmox-pve-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-pve-exporter
      version: 0.1.15
      sourceRef:
        kind: HelmRepository
        name: mahahe
        namespace: flux-system
  maxHistory: 2
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    pve:
      target:
        - 192.168.11.4:8006
      user: ${PROXMOX_USER}
      password: ${PROXMOX_PASSWORD}
