---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: radarr-secret
  data:
    - secretKey: api_key
      remoteRef:
        key: radarr
        property: api_key
