---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  upgrade:
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 5Gi
              storageClass: mayastor
              globalMounts:
                - path: /config
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [10000]
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/radarr-develop
              tag: 4.7.1.7640@sha256:fd475f0dcc5a2ef00193b17e548b4a4d4776b7b2cf32e0ff3adb5ee2aa836f20
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 7878
                  initialDelaySeconds: 45
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                memory: 100Mi
                cpu: 10m
              limits:
                memory: 500Mi
                cpu: 200m
            env:
              - name: TZ
                value: America/New_York
              - name: RADARR__INSTANCE_NAME
                value: Radarr
              - name: RADARR__PORT
                value: *port
              - name: RADARR__APPLICATION_URL
                value: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
              - name: RADARR__LOG_LEVEL
                value: info
              - name: RADARR__API_KEY
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: api_key
              - name: RADARR__POSTGRES_HOST
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: db_host
              - name: RADARR__POSTGRES_PORT
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: db_port
              - name: RADARR__POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: db_user
              - name: RADARR__POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: db_pass
              - name: RADARR__POSTGRES_MAIN_DB
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: db_main
              - name: RADARR__POSTGRES_LOG_DB
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: db_logs

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "filmstrip"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/radarr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: nas-2.lan
            path: /volume1/Media
        mountPath: /media
