---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  upgrade:
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      radarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.1.0.10309@sha256:10f94c85f605d42e5e78de928f24758b5750a4e99eee8d0ef9ff150f7a2df033
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 7878
                  initialDelaySeconds: 45
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                memory: 100Mi
                cpu: 10m
              limits:
                memory: 500Mi
                cpu: 200m
            env:
              - name: TZ
                value: America/New_York
              - name: RADARR__APP__INSTANCENAME
                value: Radarr
              - name: RADARR__AUTH__METHOD
                value: External
              - name: RADARR__AUTH__REQUIRED
                value: DisabledForLocalAddress
              - name: RADARR__AUTH__APIKEY
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: api_key
              - name: RADARR__LOG__LEVEL
                value: info
              - name: RADARR__LOG__DBENABLED
                value: "False"
              - name: RADARR__SERVER__PORT
                value: *port
              - name: RADARR__POSTGRES__HOST
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: db_host
              - name: RADARR__POSTGRES__PORT
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: db_port
              - name: RADARR__POSTGRES__USER
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: db_user
              - name: RADARR__POSTGRES__PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: db_pass
              - name: RADARR__POSTGRES__MAINDB
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: db_main

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]

    service:
      app:
        controller: radarr
        ports:
          http:
            port: *port

    ingress:
      app:
        className: "internal"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "filmstrip"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</body>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/radarr/nord.css"></body>';
            sub_filter_once on;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: radarr
      media:
        type: nfs
        server: nas-2.lan
        path: /volume1/Media
        globalMounts:
          - path: /media
