apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
  namespace: media
stringData:
  db_host: ENC[AES256_GCM,data:sEQ5RNR5PLc=,iv:dp2BLIV/DIA60gtU0ekqK+it5uIQL0H1IIja/tIoM+s=,tag:++yrfzL9cRHlrBdXXm/dhA==,type:str]
  db_port: ENC[AES256_GCM,data:Q+RTHQ==,iv:gSxqnz7HgE6Ittd3HdWJDIrOKuSfw8K8VCSFH31u76c=,tag:+i9VoPWYVaaDFj5elvPBLA==,type:str]
  db_user: ENC[AES256_GCM,data:zBWQUBJl,iv:Mv0N5n4fVz8WDx2ixCRmsLGZX+iA5rXWjs8KlbwK2Q4=,tag:7ovKpa5FTl5qOJTbos/9cA==,type:str]
  db_pass: ENC[AES256_GCM,data:Jm208bDT9twtQGleqVQmYHEMMkA9Xyr1WVTyCK+I,iv:EuDGsPcygld4i6yq6VUoDljZS5Kq364afuZFWFwMGE0=,tag:4/IuQYTMuz1Ture6f+PKig==,type:str]
  db_main: ENC[AES256_GCM,data:1dhIJMWA,iv:4q43cI0ZiFt6NlL79Sgmyutm2mVpCO56IApjghG51ug=,tag:aBRmq0xPMFdBmJGqIE2z7g==,type:str]
  db_logs: ENC[AES256_GCM,data:w4JNOj4g1rcOk5s=,iv:ChM9UpDntlAUgkvDwBQJQtAn9ycfP07SO6lCN00XZOI=,tag:yNZhrQY0vHcYXAbm0Z7caQ==,type:str]
  api_key: ENC[AES256_GCM,data:z4AjgJtcv4kucGDBkxsfXVntm3rggDxPvRtCp2t+,iv:Sl/7rCZSWlUr6cM3O9Af43mQitWB9TS4kJAOenNIzJc=,tag:S5ozxEK9QKyjyh1lD9B4cg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNzI0K2RuNWl1TS9tOFNW
        UHpINXl0ZDh5eUZ6YnhJZTdUMUtsN0xhYldNClI0RjJHTmpFenJjN3lqOVhDcC9E
        SC9xaEFyYTBGVVdPT2w3b2F2enlqUHMKLS0tIHJUemF4RUYvYVRGVXhLZUpveHNP
        N1pSSTF2SHlWOHNBc0lORnpzbXBpU0EKeKlqTrPnl764QPcP5ay4nW8M1T2UMJLu
        UgY7hIVE0h0Me9ObdNG5uaoDvrJHDniy0zbUdGcyCyB/Vvi4GpqLOQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-09-22T01:16:58Z"
  mac: ENC[AES256_GCM,data:o84iElO4iBLd6lzvFOcPOy9hOepFbsfOSU6dNs7bjggOQx+gPTwOR9C+jqzPWitTAUnZH+GvEvA1fGrdNVrxBxOXveFEARS5kpvnbfk/DpZ0Fxv01e1tT07qsiWazsyakd41Kw2oSXOU5B4OVL0PZJ/z6QGCpnlsy8J4pLikFuU=,iv:68D+by6l7HWQnyu/ftU5pPLgUT9ApC0hEAJeRVnm7XI=,tag:A7+qkM/92SPeLBH+Rf56bQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
