postgresql_global_config_options:
    - option: ENC[AES256_GCM,data:pQqopQHmXauTxXUcViSAnA==,iv:6OrF6HkqYbKoVIsR1vNAd5LcaHoaShP3CMk/IOC1QZA=,tag:lDiJEFivrOloG8CeSE0QGQ==,type:str]
      value: ENC[AES256_GCM,data:QA==,iv:in/Pp3MKJqY4Yt7MSG5ZQ8PBSSWP6XO5EHoNv69UAqE=,tag:dUMD0LfNJP8KPnIfSWSicg==,type:str]
    - option: ENC[AES256_GCM,data:u7V+,iv:sFP3ZzpINcOvdZhokhdYpmsTtcphqJF1KYc2l13DSEM=,tag:CnkxM/oEmelYRU4xprhmfw==,type:str]
      value: ENC[AES256_GCM,data:sb95,iv:0AUc1AWMDdbYIBeJ87tArHHapnlA2z4K7t3vSzRCub8=,tag:ojSvEUhOqXaQIz51QNSojQ==,type:str]
    - option: ENC[AES256_GCM,data:ZeBH/wmtJ7qqEWmYhkVkTm01PppVvvw=,iv:G+EzjWdU9xWChTGWKgb2VlAII2yAEf+3X7F9u81+N0I=,tag:LiR0ia4Yk8nzjyw9VV7nOA==,type:str]
      value: ENC[AES256_GCM,data:EbaIS0q+1jR0dLhyhOS0VS3NZS6l4tSD0wGJrRmDFpuT0muqjSWXJcWjYpCYCFespzA3Qw==,iv:un6xnaSATTAjmAJ/Wn7+hxmEC9C2Mtw6T8Dw+Q5LwxA=,tag:At5w8zoXYduO1ILL66w7hQ==,type:str]
    - option: ENC[AES256_GCM,data:J5DSw2enxk+wGb0C+w==,iv:TVEp+bMunJpDPRqxlrY8I55geWemk1vGoMHnB8H4Z1U=,tag:uTZZFP02SL/JVV/307tbAg==,type:str]
      value: ENC[AES256_GCM,data:PNub,iv:Lm3Knh453XOTsWVk+9npMongpFiusbz1/9b7l5rlq5Q=,tag:V1QkUOzToTEY2FmXOWEt1A==,type:str]
postgresql_hba_entries:
    - type: ENC[AES256_GCM,data:io4WMcQ=,iv:AWoeRdH/RavBU4oAcXfpHJVQ51zM9Jy9VIpzjuEoo9w=,tag:MZK6eAmcX2cmRNQ1+bi1wA==,type:str]
      database: ENC[AES256_GCM,data:M8up,iv:jbeUErttBiuLXWOnw+Fyn5LJAnLS019SuUERzvWnTCo=,tag:CsNSix1w4a8EMFwj5woi6Q==,type:str]
      user: ENC[AES256_GCM,data:9MCnuvK7TNQ=,iv:q7W5pnEdUC1LlhtOu7FLZsjSwecjzjbufPXGKEFZwkk=,tag:V3OhsmDk6qzSVBcqOk1bPw==,type:str]
      auth_method: ENC[AES256_GCM,data:R83YKg==,iv:8ILZzF4hHOeRaZP4426rfH0DNqQI+pxXgiiAivN58fo=,tag:Yj5wN3TRss84DZHd64azww==,type:str]
    - type: ENC[AES256_GCM,data:io4WMcQ=,iv:AWoeRdH/RavBU4oAcXfpHJVQ51zM9Jy9VIpzjuEoo9w=,tag:MZK6eAmcX2cmRNQ1+bi1wA==,type:str]
      database: ENC[AES256_GCM,data:M8up,iv:jbeUErttBiuLXWOnw+Fyn5LJAnLS019SuUERzvWnTCo=,tag:CsNSix1w4a8EMFwj5woi6Q==,type:str]
      user: ENC[AES256_GCM,data:wNii,iv:H79XqFepwfEm9qXnq3HeJcz0neqCZronJIauLRB2WZc=,tag:OxvvSdnOJS4TBBHxHLbTEw==,type:str]
      auth_method: ENC[AES256_GCM,data:R83YKg==,iv:8ILZzF4hHOeRaZP4426rfH0DNqQI+pxXgiiAivN58fo=,tag:Yj5wN3TRss84DZHd64azww==,type:str]
    - type: ENC[AES256_GCM,data:qivvgQ==,iv:yhYwcJ8LILsma+PVZtpPGFd7g4FJmxFwQoihSO3JWDI=,tag:AHY6mo7i/TU0lztC6njRWA==,type:str]
      database: ENC[AES256_GCM,data:M8up,iv:jbeUErttBiuLXWOnw+Fyn5LJAnLS019SuUERzvWnTCo=,tag:CsNSix1w4a8EMFwj5woi6Q==,type:str]
      user: ENC[AES256_GCM,data:wNii,iv:H79XqFepwfEm9qXnq3HeJcz0neqCZronJIauLRB2WZc=,tag:OxvvSdnOJS4TBBHxHLbTEw==,type:str]
      address: ENC[AES256_GCM,data:xz3p+EjhNwdjzcGJ,iv:Pm+oRGDLAv/gYOMv1UYwG5OTzU6fzqOB599JeLDy/IQ=,tag:TLtfk5wWmP0xMflpr37UjA==,type:str]
      auth_method: ENC[AES256_GCM,data:gs5N,iv:AMhD83Fn1c1IVtNAywT9agX8F3Xug/UFIQ4YyjaRZJU=,tag:oMNaqZBbhweqJFT15FHa4A==,type:str]
    - type: ENC[AES256_GCM,data:qivvgQ==,iv:yhYwcJ8LILsma+PVZtpPGFd7g4FJmxFwQoihSO3JWDI=,tag:AHY6mo7i/TU0lztC6njRWA==,type:str]
      database: ENC[AES256_GCM,data:M8up,iv:jbeUErttBiuLXWOnw+Fyn5LJAnLS019SuUERzvWnTCo=,tag:CsNSix1w4a8EMFwj5woi6Q==,type:str]
      user: ENC[AES256_GCM,data:wNii,iv:H79XqFepwfEm9qXnq3HeJcz0neqCZronJIauLRB2WZc=,tag:OxvvSdnOJS4TBBHxHLbTEw==,type:str]
      address: ENC[AES256_GCM,data:pYuCSjWuQQ==,iv:yHqqB/GCKvVvhIoRG2rVbznydcwNorZsTndWEywxzls=,tag:3NMQGUjkIUutqQR5NF5Kzg==,type:str]
      auth_method: ENC[AES256_GCM,data:gs5N,iv:AMhD83Fn1c1IVtNAywT9agX8F3Xug/UFIQ4YyjaRZJU=,tag:oMNaqZBbhweqJFT15FHa4A==,type:str]
    - type: ENC[AES256_GCM,data:qivvgQ==,iv:yhYwcJ8LILsma+PVZtpPGFd7g4FJmxFwQoihSO3JWDI=,tag:AHY6mo7i/TU0lztC6njRWA==,type:str]
      database: ENC[AES256_GCM,data:M8up,iv:jbeUErttBiuLXWOnw+Fyn5LJAnLS019SuUERzvWnTCo=,tag:CsNSix1w4a8EMFwj5woi6Q==,type:str]
      user: ENC[AES256_GCM,data:wNii,iv:H79XqFepwfEm9qXnq3HeJcz0neqCZronJIauLRB2WZc=,tag:OxvvSdnOJS4TBBHxHLbTEw==,type:str]
      address: ENC[AES256_GCM,data:+8ZUiNpE54bMLQCYur0=,iv:TiqmGTrG2UNKiDP6GaOct8U8EKnXwqkwin0x6w4LI78=,tag:ZkJjILS+pCULVfcMF6v/9A==,type:str]
      auth_method: ENC[AES256_GCM,data:gs5N,iv:AMhD83Fn1c1IVtNAywT9agX8F3Xug/UFIQ4YyjaRZJU=,tag:oMNaqZBbhweqJFT15FHa4A==,type:str]
postgresql_databases:
    - name: ENC[AES256_GCM,data:Y1StRF5JlSR5W+MODw==,iv:wh+Ko9IdYYTUpSaexOLXQgBF1U1O6mkosqRd9gY95nU=,tag:8KuyqjQOBI14u8yDxK9Etw==,type:str]
postgresql_users:
    - name: ENC[AES256_GCM,data:FE4rihE=,iv:wH1RZJKOOzLEp6hhdjlrSE/FPga6b7abhLA8BGqjXq8=,tag:rvUDde7gxHBQtfdk8Jiyug==,type:str]
      password: ENC[AES256_GCM,data:mrZLb6qnmSRt,iv:u+5KQZJiXeKLWdqb8dNq4W7Io7j/mvRA6bnkswBowOw=,tag:LP0GhJDpSB9XT6h5dlbbgg==,type:str]
    - name: ENC[AES256_GCM,data:aQ6Ih3hRwLZwyLMKFA==,iv:vvB9KbRzmOqAUriWoujRM54njUBRt31LrBvvunO5BzM=,tag:OZHYEQB/MKdt7TiTmok87A==,type:str]
      password: ENC[AES256_GCM,data:LwqWxqsW+l7ZG6Q=,iv:UnnyjZC7dU4pH+90I1ju4kwQpNGq7o2NoNuf4gB8NlU=,tag:qn9fcOPFmCjJeANhIgbPWw==,type:str]
      db: ENC[AES256_GCM,data:n7fbG9arr9IppsiPgQ==,iv:QVsUYgucel60BU7YcnzMVtltLtH8xm+4XywjDeI4o/I=,tag:95HeY83sQupEESKvzbhWig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRGVqYUxYSitOT3RhYnRx
            VWtEa280QmZtZXk3Z3I3bUNucVg4ZzM4RUVFCk5nRndjdnlXUy9ibFhlZFFsMDlh
            RXhQbW0rN1NFYlBEbUN6Yk1DcnR3UjQKLS0tIGVmMUx3SnEvL3RQdjlIMWpTSkRo
            SXVNbmMydUxOczhwdkc0N0NITjc4K2MKOKrQFfXC/7Jd2PKGU+i3pg8WLxqIXgSD
            y9HtiKZNfJ5ud1fZxzODcbzU8wxmSNQj8Ak6Ci0tU4MtnfGR+6/ZZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-22T00:51:26Z"
    mac: ENC[AES256_GCM,data:vUnvZaErtLEY1p/06ikO+vMpAZraW9Arextp9T3fYR60EAuLsaSwBI3PSdUPFW2FzotfLCimrZHR+cHYowe+fet+qi4yzxJFpxxhuRX9eeQsRiHySJOrRB7IVN5v3pdSYCFXx+bYvBPzXneP9DaMNrvGB7v+l7t0ljYFQNHJc9k=,iv:8ODILhiWMlhNsgppw7ng13h4e+gnLnFRN2uEB0fs468=,tag:KvPbKog2hpQuQh68PMLmUQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
