---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 10Gi
