---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: donetick
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      donetick:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: donetick/donetick
              tag: v0.1.35
            env:
              - name: DT_DATABASE_TYPE
                value: postgres
              - name: DT_DATABASE_HOST
                valueFrom:
                  secretKeyRef:
                    name: donetick-secret
                    key: db_host
              - name: DT_DATABASE_PORT
                valueFrom:
                  secretKeyRef:
                    name: donetick-secret
                    key: db_port
              - name: DT_DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    name: donetick-secret
                    key: db_user
              - name: DT_DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: donetick-secret
                    key: db_pass
              - name: DT_DATABASE_NAME
                valueFrom:
                  secretKeyRef:
                    name: donetick-secret
                    key: db_name
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/ping
                    port: &port 2021
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 500Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: donetick
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
