apiVersion: v1
kind: Secret
metadata:
  name: donetick-secret
  namespace: default
stringData:
  db_host: ENC[AES256_GCM,data:+W6kdOV3Ojmn+g==,iv:RV+LlKcZ5Qf+I4LeSw7u6IkS/SQOHb0aIgI1ng6ljlQ=,tag:2tcbJAK60od6Eqx7Oql35g==,type:str]
  db_port: ENC[AES256_GCM,data:fwGNEg==,iv:HLRLBcysMtISJ58YePSYlBlPesMKmaU8pL8O6MsZTuk=,tag:S4uncVcHmB4xt+hOOZseCw==,type:str]
  db_user: ENC[AES256_GCM,data:Obo5Q9SKan8=,iv:3PN8USgK/6k5HxZAIX973a00DTY8F+HLT8D6nYTIFxw=,tag:ak5Bz4XXvii8PBukwy4QOQ==,type:str]
  db_pass: ENC[AES256_GCM,data:f4wdJcBbBJSyYEW2rPhj7r/mkeqxUMNhQhKQ6sNP,iv:DmworPT3REdYbt8+aDst9IT5JZkJptU7fa3Iyl9ndy4=,tag:/Ln6pBGXkBCdRROJOYNpwg==,type:str]
  db_name: ENC[AES256_GCM,data:FWrR912f6cU=,iv:rAn6j0Prg7GBI6Oj0a3lPkZsCj6WnrYI4rYOEGOAEfo=,tag:8EEWMVZDzSK3wSVSvDFHGA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OUR3TUVpMVNXeEpITDRy
        OVRSVC9idHBXZHdUbE5LUHZTeW9PQkw5V3dBCmt6cCtONExsQno3ZHRSQVZ0UGZM
        aWZvYi9pVVBMRlhNY3BGZVAyd0FIalkKLS0tIGdRdlhNOEtwN0lvdDBqMlJlTGhB
        bWE5ZWNmQUhvMU51dExid2lnVVE3Um8K3U+i3fr68C2MKCTnkwb1h00jmKkgEndF
        sCVgMvM5E7cMhr8eyOpz4+ZhoKMlij3PuCtimuVOICrAJrs9FZQgGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-22T20:36:15Z"
  mac: ENC[AES256_GCM,data:8ecZvsM0/7SSEQesgSgyzLFbObjQpYZKxvg+sOUITvW3bzHbljPB/Bv85kIIhvAEz7lDxKU/ccjHvH5muvnCy5e6vh6nVqhOEbAvV4YM3ip7vgpoUUX0bNHAr+5lsVX2Gdz5WwJx+SyEdiGrqcwAdLTyJubzDgCHKW6O4BgAYI0=,iv:ROsxR5ISrEqH3nNbNWRY5O9pwSpcihCXaeKKjIJWf0U=,tag:fOhuhLRPA7q0MTanbRMiqw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
