---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: sabnzbd-secret
  data:
    - secretKey: api_key
      remoteRef:
        key: sabnzbd
        property: api_key
    - secretKey: nzb_key
      remoteRef:
        key: sabnzbd
        property: nzb_key
