---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      sabnzbd:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.5@sha256:485440a3e9209a3515c01e1c73d6088726491a292302a721d4cb9e7c6375c768
            resources:
              requests:
                cpu: 25m
                memory: 100Mi
              limits:
                memory: 3Gi
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: api_key
              SABNZBD__NZB_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: nzb_key
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd.media.svc.cluster.local,
                sabnzbd.${SECRET_DOMAIN}

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 65539

    service:
      app:
        controller: sabnzbd
        ports:
          http:
            port: *port

    ingress:
      app:
        className: "internal"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/sabnzbd/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "sabnzbd.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: sabnzbd
      media:
        type: nfs
        server: nas-2.lan
        path: /volume1/Media
        globalMounts:
          - path: /media
