---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dispatcharr
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      dispatcharr:
        containers:
          app:
            image:
              repository: ghcr.io/dispatcharr/dispatcharr
              tag: 0.15.1
            env:
              DISPATCHARR_ENV: aio
              REDIS_HOST: localhost
              CELERY_BROKER_URL: redis://localhost:6379/0
              DISPATCHARR_LOG_LEVEL: info
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 9191
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
                gpu.intel.com/i915: "1"
              limits:
                memory: 2Gi
                gpu.intel.com/i915: "1"

    # defaultPodOptions:
      # https://github.com/Dispatcharr/Dispatcharr/blob/523a127c81965a25a0246a28151cc2118ca11cf9/docker/entrypoint.sh
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 65534
      #   runAsGroup: 65534
      #   fsGroup: 65534
      #   fsGroupChangePolicy: OnRootMismatch
      #   seccompProfile:
      #     type: RuntimeDefault

    service:
      app:
        controller: dispatcharr
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: dispatcharr
