---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: qbittorrent-secret
    template:
      engineVersion: v2
  data:
    - secretKey: VPN_SERVICE_PROVIDER
      remoteRef:
        key: vpn/provider
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: vpn/wireguard_key
    - secretKey: SERVER_COUNTRIES
      remoteRef:
        key: vpn/server_countries
    - secretKey: SERVER_CITIES
      remoteRef:
        key: vpn/server_cities
    - secretKey: GLUETUN_CONTROL_API_KEY
      remoteRef:
        key: gluetun/control_api_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-gluetun-auth-config
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: qbittorrent-gluetun-auth-config
    template:
      engineVersion: v2
      data:
        auth-config.toml: |
          [[roles]]
          name = "qbittorrent"
          routes = ["GET /v1/portforward", "GET /v1/vpn/status"]
          auth = "apikey"
          apikey = "{{ .control_api_key }}"
  data:
    - secretKey: control_api_key
      remoteRef:
        key: gluetun/control_api_key
