apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: synology-csi-retain
