---
inline_manifests:
  - name: cilium
    run: kustomize
    files:
      - name: values.yaml
        contents:
          cluster:
            name: home_cluster
            id: 1
          ipam:
            mode: kubernetes
          kubeProxyReplacement: strict
          securityContext:
            capabilities:
              ciliumAgent:
                - CHOWN
                - KILL
                - NET_ADMIN
                - NET_RAW
                - IPC_LOCK
                - SYS_ADMIN
                - SYS_RESOURCE
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
              cleanCiliumState:
                - NET_ADMIN
                - SYS_ADMIN
                - SYS_RESOURCE
          cgroup:
            autoMount:
              enabled: false
            hostRoot: /sys/fs/cgroup
          ipv4NativeRoutingCIDR: 10.244.0.0/16
          k8sServiceHost: localhost
          k8sServicePort: 7445
      - name: kustomization.yaml
        contents:
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          helmCharts:
            - name: cilium
              repo: https://helm.cilium.io/
              version: 1.14.2
              releaseName: cilium
              namespace: kube-system
              valuesFile: values.yaml
          commonAnnotations:
            meta.helm.sh/release-name: cilium
            meta.helm.sh/release-namespace: kube-system
          commonLabels:
            app.kubernetes.io/managed-by: Helm
