---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  targetNamespace: synology-csi
  path: ./cluster/apps/synology-csi/synology-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  interval: 1h
  retryInterval: 1m
  timeout: 15m
