---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-b2
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: "0 3 * * *"
  restic:
    pruneIntervalDays: 7
    repository: volsync-restic-b2
    cacheCapacity: ${VOLSYNC_CACHE_CAPACITY:=1Gi}
    copyMethod: ${VOLSYNC_COPY_METHOD:=Snapshot}
    storageClassName: ${VOLSYNC_STORAGECLASS:=synology-csi-retain}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=synology-csi-snapclass}
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      last: "7"
