kea_dhcp_ddns:
  enabled: true
  config:
    ip-address: "127.0.0.1"
    port: 53001
    dns-server-timeout: 500
    ncr-protocol: "UDP"
    ncr-format: "JSON"
    control-socket:
      socket-type: unix
      socket-name: "/tmp/kea-ddns-ctrl-socket"
    tsig-keys: []
    forward-ddns:
      ddns-domains:
        - name: internal.my.home.
          dns-servers:
            - ip-address: 127.0.0.1
              port: 53
    reverse-ddns:
      ddns-domains: []

    loggers:
      - name: kea-dhcp-ddns
        output_options:
          - output: /var/log/kea/ddns.log
        severity: INFO
        debuglevel: 1
