---
# https://kea.readthedocs.io/en/kea-2.4.0/arm/dhcp4-srv.html
kea_dhcp4:
  enabled: true
  config:
    # Global timers specified here apply to all subnets, unless there are
    # subnet specific values defined in particular subnets.
    renew-timer: 900
    rebind-timer: 1800
    valid-lifetime: 3600

    # Add names of your network interfaces to listen on.
    interfaces-config:
      # See section 8.2.4 for more details. You probably want to add just
      # interface name (e.g. "eth0" or specific IPv4 address on that
      # interface name (e.g. "eth0/192.168.42.1").
      interfaces:
        - eth0

    # Use Memfile lease database backend to store leases in a CSV file.
    # Depending on how Kea was compiled, it may also support SQL databases
    # (MySQL and/or PostgreSQL) and even Cassandra. Those database backends
    # require more parameters, like name, host and possibly user and password.
    # There are dedicated examples for each backend. See Section 7.2.2 "Lease
    # Storage" for details.
    lease-database:
      name: "/var/lib/kea/dhcp4.leases"
      type: memfile
      persist: true
      lfc-interval: 0

    # Setup reclamation of the expired leases and leases affinity.
    # Expired leases will be reclaimed every 10 seconds. Every 25
    # seconds reclaimed leases, which have expired more than 3600
    # seconds ago, will be removed. The limits for leases reclamation
    # are 100 leases or 250 ms for a single cycle. A warning message
    # will be logged if there are still expired leases in the
    # database after 5 consecutive reclamation cycles.
    expired-leases-processing:
      reclaim-timer-wait-time: 10
      flush-reclaimed-timer-wait-time: 25
      hold-reclaimed-time: 3600
      max-reclaim-leases: 100
      max-reclaim-time: 250
      unwarned-reclaim-cycles: 5

    dhcp-ddns:
      # Connectivity parameters
      enable-updates: true
      server-ip: "127.0.0.1"
      server-port: 53001
      sender-ip: ""
      sender-port: 0
      max-queue-size: 1024
      ncr-protocol: "UDP"
      ncr-format: "JSON"

    # Behavioral parameters (global)
    ddns-send-updates: true
    ddns-override-no-update: false
    ddns-override-client-update: false
    ddns-replace-client-name: "never"
    ddns-update-on-renew: true
    # ddns-conflict-resolution-mode: "check-with-dhcid"
    ddns-generated-prefix: "myhost"
    hostname-char-set: "[^A-Za-z0-9.-]"
    hostname-char-replacement: "x"

    subnet4:
      # This defines the whole subnet. Kea will use this information to
      # determine where the clients are connected. This is the whole
      # subnet in your network. This is mandatory parameter for each
      # subnet.
      - subnet: 192.168.42.1/24
        ddns-qualifying-suffix: "internal.my.home."

        # Pools define the actual part of your subnet that is governed
        # by Kea. Technically this is optional parameter, but it's
        # almost always needed for DHCP to do its job. If you omit it,
        # clients won't be able to get addresses, unless there are
        # host reservations defined for them.
        pools:
          - pool: "192.168.42.100 - 192.168.42.255"

        # These are options that are subnet specific. In most cases,
        # you need to define at least routers option, as without this
        # option your clients will not be able to reach their default
        # gateway and will not have Internet connectivity.
        option-data:
          - name: routers
            data: "192.168.42.1"

        # Kea offers host reservations mechanism. Kea supports reservations
        # by several different types of identifiers: hw-address
        # (hardware/MAC address of the client), duid (DUID inserted by the
        # client), client-id (client identifier inserted by the client) and
        # circuit-id (circuit identifier inserted by the relay agent).

        # Kea also support flexible identifier (flex-id), which lets you
        # specify an expression that is evaluated for each incoming packet.
        # Resulting value is then used for as an identifier.

        # Note that reservations are subnet-specific in Kea. This is
        # different than ISC DHCP. Keep that in mind when migrating
        # your configurations.
        reservations:
          []
          # - hw-address: 00:01:02:03:04:05
          #   ip-address: '192.168.42.201'

    # Logging configuration starts here. Kea uses different loggers to log various
    # activities. For details (e.g. names of loggers), see Chapter 18.
    loggers:
      - name: kea-dhcp4
        output_options:
          - output: /var/log/kea/dhcp4.log
        severity: INFO
        debuglevel: 1
