---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-tautulli
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: synology-csi-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-tautulli
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: synology-csi-retain
