---
dns:
  hosts:
    dns-1:
      ansible_host: 192.168.42.10

db:
  hosts:
    db-1:
      ansible_host: db-1.lan

kube:
  children:
    kube-control-plane:
      hosts:
        k8s-server-1:
          ansible_host: k8s-server-1.lan
          kube:
            machine:
              network:
                interfaces:
                  - interface: enx3eb3c406fc9f
                    dhcp: true
                    vip:
                      ip: 192.168.42.42
    kube-worker:
      hosts:
        k8s-worker-1:
          ansible_host: k8s-worker-1.lan
          kube:
            machine:
              network:
                interfaces:
                  - interface: enxa29e166d29cf
                    dhcp: true
        k8s-worker-2:
          ansible_host: k8s-worker-2.lan
          kube:
            machine:
              network:
                interfaces:
                  - interface: enx8a841969a9ab
                    dhcp: true
