---
dns:
  hosts:
    dns-1:
      ansible_host: 192.168.42.10

db:
  hosts:
    db-1:
      ansible_host: db-1.lan

kube:
  children:
    kube-control-plane:
      hosts:
        k8s-server-1:
          ansible_host: k8s-server-1.lan
          kube:
            machine:
              install:
                wipe: true
                extensions:
                  - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:cef7e23d0f6cbf68176bca038c2491d3ef9583e2e8c9fa5c0fb844ce1c791f2e
              network:
                interfaces:
                  - interface: enx3eb3c406fc9f
                    dhcp: true
                    vip:
                      ip: 192.168.42.42
    kube-worker:
      hosts:
        k8s-worker-1:
          ansible_host: k8s-worker-1.lan
          kube:
            machine:
              install:
                extensions:
                  - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:cef7e23d0f6cbf68176bca038c2491d3ef9583e2e8c9fa5c0fb844ce1c791f2e
              network:
                interfaces:
                  - interface: enxa29e166d29cf
                    dhcp: true
        k8s-worker-2:
          ansible_host: k8s-worker-2.lan
          kube:
            machine:
              install:
                disk: /dev/nvme0n1
                wipe: true
                extensions:
                  - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:cef7e23d0f6cbf68176bca038c2491d3ef9583e2e8c9fa5c0fb844ce1c791f2e
              network:
                interfaces:
                  - interface: enp2s0
                    dhcp: true
        k8s-worker-3:
          ansible_host: k8s-worker-3.lan
          kube:
            machine:
              install:
                disk: /dev/nvme0n1
                wipe: true
                extensions:
                  - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:cef7e23d0f6cbf68176bca038c2491d3ef9583e2e8c9fa5c0fb844ce1c791f2e
              network:
                interfaces:
                  - interface: enp2s0
                    dhcp: true
