---
db:
  hosts:
    data-1:
      ansible_host: data-1.lan

kube:
  children:
    kube-control-plane:
      hosts:
        k8s-server-1:
          ansible_host: k8s-server-1.lan
          kube:
            machine:
              install:
                disk: /dev/nvme0n1
              network:
                interfaces:
                  - interface: enp2s0
                    dhcp: true
                    vip:
                      ip: 192.168.42.42
    kube-worker:
      hosts:
        k8s-worker-1:
          ansible_host: k8s-worker-1.lan
          kube:
            machine:
              install:
                disk: /dev/nvme0n1
              network:
                interfaces:
                  - interface: enp2s0
                    dhcp: true
              sysctls:
                vm.nr_hugepages: "1024"
        k8s-worker-2:
          ansible_host: k8s-worker-2.lan
          kube:
            machine:
              install:
                disk: /dev/nvme0n1
              network:
                interfaces:
                  - interface: enp2s0
                    dhcp: true
