---
dns:
  hosts:
    dns-1:
      ansible_host: 192.168.42.10

db:
  hosts:
    db-1:
      ansible_host: db-1.lan

kube:
  children:
    kube-control-plane:
      hosts:
        k8s-server-1:
          ansible_host: k8s-server-1.lan
          kube:
            machine:
              install:
                disk: /dev/sda
              network:
                interfaces:
                  - interface: enx3eb3c406fc9f
                    dhcp: true
                    vip:
                      ip: 192.168.42.42
        k8s-server-2:
          ansible_host: k8s-server-2.lan
          kube:
            machine:
              install:
                disk: /dev/nvme0n1
              network:
                interfaces:
                  - interface: enp2s0
                    dhcp: true
                    vip:
                      ip: 192.168.42.42
        k8s-server-3:
          ansible_host: k8s-server-3.lan
          kube:
            machine:
              install:
                disk: /dev/nvme0n1
              network:
                interfaces:
                  - interface: enp2s0
                    dhcp: true
                    vip:
                      ip: 192.168.42.42
    kube-worker:
      hosts:
        k8s-worker-1:
          ansible_host: k8s-worker-1.lan
          kube:
            machine:
              install:
                disk: /dev/sda
              network:
                interfaces:
                  - interface: enxa29e166d29cf
                    dhcp: true
        k8s-worker-2:
          ansible_host: k8s-worker-2.lan
          kube:
            machine:
              install:
                disk: /dev/nvme0n1
              network:
                interfaces:
                  - interface: enp2s0
                    dhcp: true
              sysctls:
                vm.nr_hugepages: "1024"
