---
dns:
  hosts:
    dns-1:
      ansible_host: 192.168.42.10

kube:
  children:
    kube-control-plane:
      hosts:
        k8s-server-1:
          ansible_host: k8s-server-1.lan
    kube-worker:
      hosts:
        k8s-worker-1:
          ansible_host: k8s-worker-1.lan
