apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-prowlarr-0
  namespace: media
  labels:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: prowlarr
    app.kubernetes.io/name: prowlarr
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: csi.san.synology.com
    volume.kubernetes.io/storage-provisioner: csi.san.synology.com
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-5109ce12-9d57-477c-91e5-31ea2cef02ad
  storageClassName: synology-csi-retain
  volumeMode: Filesystem
