apiVersion: v1
kind: Pod
metadata:
  name: shell
  namespace: media
spec:
  containers:
    - name: shell
      image: ubuntu
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: config
          mountPath: /config
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: config-prowlarr-0
