---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudflared
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-dns
  path: ./cluster/apps/networking/cloudflared/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
