---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: immich
      version: 0.10.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            env:
              TZ: America/New_York
              DB_HOSTNAME: immich-postgres-rw
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-app
                    key: username
              DB_DATABASE_NAME: immich
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-app
                    key: password

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    immich:
      metrics:
        enabled: true
      persistence:
        library:
          type: nfs
          server: nas-2.lan
          path: /volume1/Photos

    # job-queues not persisted, change storage class to persist.
    valkey:
      enabled: true

    server:
      controllers:
        main:
          containers:
            main:
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  memory: 2Gi
      ingress:
        main:
          enabled: true
          className: internal
          hosts:
            - host: &host "immich.${SECRET_DOMAIN}"
              paths:
                - path: /
                  service:
                    identifier: main
          tls:
            - hosts:
                - *host

    machine-learning:
      enabled: true
      controllers:
        main:
          containers:
            main:
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              resources:
                requests:
                  cpu: 100m
                  memory: 512Mi
                  gpu.intel.com/i915: "1"
                limits:
                  memory: 2Gi
                  gpu.intel.com/i915: "1"
      persistence:
        cache:
          enabled: true
          type: persistentVolumeClaim
          accessMode: ReadWriteOnce
          size: 10Gi
          storageClassName: synology-csi
      defaultPodOptions:
        nodeSelector:
          intel.feature.node.kubernetes.io/gpu: "true"
