---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: media
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.4.0
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: synology-csi
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS vectors;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
  postgresql:
    shared_preload_libraries:
      - vectors.so
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
