---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: cloudflared-secret
  data:
    - secretKey: TUNNEL_ID
      remoteRef:
        key: cloudflared
        property: TUNNEL_ID
    - secretKey: credentials.json
      remoteRef:
        key: cloudflared
        property: credentials.json
