---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dispatcharr
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: dispatcharr
  components:
    - ../../../../components/volsync
  path: ./cluster/apps/media/dispatcharr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  postBuild:
    substitute:
      APP: dispatcharr
      VOLSYNC_CAPACITY: 5Gi
  wait: false
  interval: 1h
  timeout: 15m
