---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: code-server-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/coder/code-server/ci/helm-chart
  timeout: 3m
