---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s-charts.yaml
  - external-secrets.yaml
  - grafana-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - longhorn-charts.yaml
  - mahahe.yaml
  - metallb-charts.yaml
  - prometheus-community-charts.yaml
