---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      overseerr:
        containers:
          app:
            image:
              repository: ghcr.io/sct/overseerr
              tag: 1.35.0@sha256:6197516c9d7b58ccf113455e32aafb94df5d91995fe50e8c2cae6ba6c7c7b7de
            env:
              TZ: America/New_York
              LOG_LEVEL: "info"
              PORT: &port 80
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                cpu: 500m
                memory: 500Mi

    service:
      app:
        controller: overseerr
        ports:
          http:
            port: *port

    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/overseerr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "request.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: overseerr
        globalMounts:
          - path: /app/config
