---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.25.6.5577-c8bd13540
    env:
      TZ: "America/New_York"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 100
      fsGroup: 100
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"
        hosts:
          - host: &host "plex.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NFS_SERVER}
            path: /volume1/Lab/config/plex
        mountPath: /config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NFS_SERVER}
            path: /volume1/Media
        mountPath: /media
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
