---
collections:
  - name: community.general
    version: 6.0.0
  - name: community.sops
    version: 1.4.1
  # - name: community.docker
  # version: 2.2.0
roles:
  - name: geerlingguy.docker
    version: 6.0.3
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.3.0
