---
collections:
  - name: community.general
    version: 7.1.0
  - name: community.sops
    version: 1.6.4
  # - name: community.docker
  # version: 2.2.0
roles:
  - name: geerlingguy.docker
    version: 6.1.0
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.2
