---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: synology-csi
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    images:
      plugin:
        image: ghcr.io/zebernst/synology-csi
        pullPolicy: IfNotPresent
        tag: v1.1.2
    clientInfoSecret:
      create: false
      name: synology-csi-client-info
    storageClasses:
      delete:
        parameters:
          dsm: nas-2.lan
          fsType: ext4
          location: /volume2
          protocol: iscsi
      retain:
        isDefault: true
        parameters:
          dsm: nas-2.lan
          fsType: ext4
          location: /volume2
          protocol: iscsi
