apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:Iqjqq+ykJxPZbKs3yBmqwsMrRYH9SFH6Iqi75PmAH7668Uog2kqDKueJRcdjsM6hA76a8fCJht/bcj98xGmyCAVmokPky4ROWcnmelwUmoy30nv7/pVQx/Yt1UBuFdY9nOQEYoTF+uv/odi7+r/xsQ==,iv:cNgEi1vkVlAe7mjxr2+hJF2UpbY1QI28+9HgDQDgUSQ=,tag:g0X19pr7VRXFC/+AymPXNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYXFER1NwaGw0aGpHUkF4
            WXJoQzVoVEg3WVRWSEhXTzM5aVNzK2dVVWdrCjY1Y204c0pBVXVNR0dBTnQxYkY4
            Z0M5UExobDU4c0g1Sko1U2UwS3BwdVEKLS0tIG9hWWZCZ0JLMUJGb3pLSXpGRDVm
            TTlkQ2ttSEJMVXFCMmU3K0FDTnp5cXcKjhgUslUAN3HSPaCaPqLTUI/BWiDg4uqz
            XwTDaPW3BvryS4C2TowgLrmEaGPmlTBfkuaBbKW0SsngbwWHaXNxpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-18T21:31:02Z"
    mac: ENC[AES256_GCM,data:aNxLPZQZKMZTfnVYf0kWN3Lo4L65uK9qFkLEeXAECBQceN8H5r050cPnuXudOHpElkQXpkwJN5gp+KSH7f3c0d13u1R376M87ImC0w3OWQzovqOQrqKW/VuR0tIemMR7uRu6uSnFGcGeXb9zgOCkTSMazx4IsNowekk7tkSk3k4=,iv:+5gsHvLG0y89d6D9W+lt8DGKbqXhRoZ4yl+aXzbIyxM=,tag:j8lkkgl9IkncgJNMxR26ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
