---
- name: install kea-dhcp
  package:
    name: kea
    state: present

- name: configure kea-dhcp
  template:
    src: "{{ item + '.conf.j2' }}"
    dest: "{{ '/etc/kea/' + item + '.conf' }}"
    mode: 0644
  notify:
    - restart kea services
  loop:
    - kea-ctrl-agent
    - kea-dhcp-ddns
    - kea-dhcp4
    - kea-dhcp6
    - keactrl

