---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-webhooks
  namespace: flux-system
spec:
  path: ./cluster/apps/flux-system/webhooks/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 1h
  retryInterval: 1m
  timeout: 5m
