---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: recyclarr
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: recyclarr
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: sonarr
    - name: radarr
  path: ./cluster/apps/media/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  postBuild:
    substitute:
      APP: recyclarr
      VOLSYNC_CAPACITY: 1Gi
  wait: false
  interval: 1h
  timeout: 15m
