---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  path: ./cluster/apps/external-secrets/external-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 1h
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-secret-store
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-operator
  path: ./cluster/apps/external-secrets/external-secrets/cluster-secret-store
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 1h
  timeout: 5m
