---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mayastor
  namespace: mayastor
spec:
  interval: 30m
  chart:
    spec:
      chart: mayastor
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: mayastor
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    etcd:
      replicaCount: 1
      persistence:
        storageClassName: manual
    # obs:
    #   callhome:
    #     enabled: false
    loki-stack:
      enabled: false
