---
# https://mayastor.gitbook.io/introduction/quickstart/configure-mayastor#create-mayastor-storageclass-s
# 2 node replication (tolerates 1 node failure)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor
parameters:
  ioTimeout: "30"
  protocol: nvmf
  repl: "2"
provisioner: io.openebs.csi-mayastor
