---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snmp-exporter-dell-idrac-1
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    fullnameOverride: snmp-exporter-dell-idrac-1
    image:
      repository: quay.io/prometheus/snmp-exporter
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: snmp-exporter-dell-idrac-1
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: snmp-exporter-dell-idrac-1
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      params:
        enabled: true
        conf:
          module:
            - dell_idrac
          target:
            - ${DELL_IDRAC_ADDR}
      path: /snmp
      # interval: 60s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
