---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-rclone
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: volsync-rclone
  data:
    - secretKey: rclone.conf
      remoteRef:
        key: volsync/rclone.conf
