---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-gateway
  namespace: flux-system
spec:
  path: ./cluster/apps/networking/k8s-gateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  interval: 1h
  timeout: 5m
