---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: 6.53.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false

      commonConfig:
        replication_factor: 1

      storage:
        type: filesystem

      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      limits_config:
        retention_period: 168h # 7 days
        ingestion_rate_mb: 16
        ingestion_burst_size_mb: 32

      compactor:
        working_directory: /var/loki/compactor
        retention_enabled: true
        delete_request_store: filesystem

    singleBinary:
      replicas: 1
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
      persistence:
        enabled: true
        storageClass: synology-csi
        size: 10Gi

    # Disable components not needed for SingleBinary mode
    gateway:
      enabled: false
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    # Disable caches for small deployment
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false

    # Monitoring
    monitoring:
      serviceMonitor:
        enabled: true
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false

    test:
      enabled: false
