---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicaCount: 3
      extraEnvs:
        - name: TZ
          value: America/New_York
      extraArgs:
        default-ssl-certificate: "networking/${DOMAIN/./-}-tls"
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
      service:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - ${CLUSTER_INGRESS_ADDR}
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      ingressClassResource:
        default: true
      resources:
        requests:
          memory: 250Mi
          cpu: 100m
        limits:
          memory: 1000Mi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: networking
          namespaceSelector:
            any: true
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.24.0
      extraEnvs:
        - name: TEMPLATE_NAME
          value: ghost
        - name: SHOW_DETAILS
          value: "false"
