---
- hosts:
    - all
  become: true
  gather_facts: true
  any_errors_fatal: true
  # roles:
  #   - ubuntu
  tasks:
    - name: Install docker
      ansible.builtin.apt:
        name:
          - docker.io
        install_recommends: false
        update_cache: true
        cache_valid_time: 3600
        autoclean: true
        autoremove: true
      register: apt_install_docker
      retries: 5
      until: apt_install_docker is success
    - name: Mount NFS
      mount:
        fstype: nfs
        opts: defaults
        dump: 0
        passno: 0
        state: mounted
        src: "{{nfs_source}}"
        path: "/nfs"
# Follow:
# https://github.com/lloesche/valheim-server-docker#basic-docker-usage
