---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tautulli
  namespace: flux-system
spec:
  path: ./cluster/apps/media/tautulli/app
  targetNamespace: media
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  interval: 1h
  retryInterval: 1m
  timeout: 15m
  commonMetadata:
    labels:
      app.kubernetes.io/name: plex
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: tautulli
      VOLSYNC_CAPACITY: 5Gi
