---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.35.0
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
