---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-csi-client-info
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: synology-csi-client-info
  data:
    - secretKey: client-info.yml
      remoteRef:
        key: synology-csi/client-info.yml
