---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  interval: 1h
  chart:
    spec:
      chart: synology-csi
      version: 0.9.4
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    clientInfoSecret:
      create: false
      name: synology-csi-client-info
    storageClasses:
      synology-csi:
        isDefault: true
        reclaimPolicy: Delete
        parameters:
          dsm: nas-1.lan
          fsType: ext4
          location: /volume1
          protocol: iscsi
      synology-csi-retain:
        # TODO: fix me
        # reclaimPolicy: Retain
        parameters:
          dsm: nas-1.lan
          fsType: ext4
          location: /volume1
          protocol: iscsi
