apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:RF8joTY6owSog3L24vMFEWRDOUQw/z1gWunxYP2cF16MTWebos4wj3R/OdZ+91Jap+6El2MW1IydlyXSs3InqH6CHDl0dIKmfChIFT/E0ejPSTMVyZLnlkM+EfAr2NHL2YAjB12tD5wNcCgFWLUm8Wo+Ja0+q4rDLUpa,iv:6hJSNQGu+ns1UB/WwqX8vqqnptLZPxzw6B+uJiIwXlY=,tag:1D276siTegB9jlLI0x0fZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYXFER1NwaGw0aGpHUkF4
            WXJoQzVoVEg3WVRWSEhXTzM5aVNzK2dVVWdrCjY1Y204c0pBVXVNR0dBTnQxYkY4
            Z0M5UExobDU4c0g1Sko1U2UwS3BwdVEKLS0tIG9hWWZCZ0JLMUJGb3pLSXpGRDVm
            TTlkQ2ttSEJMVXFCMmU3K0FDTnp5cXcKjhgUslUAN3HSPaCaPqLTUI/BWiDg4uqz
            XwTDaPW3BvryS4C2TowgLrmEaGPmlTBfkuaBbKW0SsngbwWHaXNxpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:51:02Z"
    mac: ENC[AES256_GCM,data:7gYM7j+hXYAqov9Fm67TDlgA7LRmuNINm744BqqVmwEznM5kCMHz/b37FMx4ul43HU/Bc9bcs3HkYS/k5XG0iJuMEVoQZKndoRG2m9ddWYi7mToCybBiHOJekAigAivbq8XiYW87LpYgG8Ci5iTLuo0Irlz7YXZ+xixGKTP7WmM=,iv:5khIVyKkz/R+4TIqyjOr3TvZE0bcslodeeB1lOao/2g=,tag:pXz4t+Pe6c4wSfAI8pogyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
