---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex
  namespace: flux-system
spec:
  dependsOn:
    - name: intel-device-plugins-gpu
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: plex
  components:
    - ../../../../components/volsync
  path: ./cluster/apps/media/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  postBuild:
    substitute:
      APP: plex
      VOLSYNC_CAPACITY: 30Gi
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
