---
- name: Fetch kubectl config
  any_errors_fatal: true
  hosts:
    - server
  tasks:
    - name: Get Kubernetes config file
      run_once: true
      ansible.builtin.slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_base64
      when: ansible_hostname == hostvars[groups['server'][0]]['ansible_hostname']

    - name: Write Kubernetes config file with the correct cluster address
      ansible.builtin.copy:
        content: "{{ kubeconfig_base64.content | b64decode | replace('127.0.0.1', vars['k3s_registration_address']) }}"
        dest: "{{ playbook_dir }}/../../../kubeconfig"
        mode: 0644
      delegate_to: localhost
      run_once: true
      when: ansible_hostname == hostvars[groups['server'][0]]['ansible_hostname']
