---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: media
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.0-0.5.3@sha256:267f6cbb32af6e109e138a143c7e9dd5d44d68433ec2303f0c30e745c788d1a9
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: synology-csi
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS vector CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
  postgresql:
    shared_preload_libraries:
      - vchord.so
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
