---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: qbittorrent
  dependsOn:
    - name: generic-device-plugin
  components:
    - ../../../../components/volsync
  path: ./cluster/apps/media/qbittorrent/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  postBuild:
    substitute:
      APP: qbittorrent
      VOLSYNC_CAPACITY: 1Gi
  wait: false
  interval: 1h
  retryInterval: 1m
  timeout: 15m
