---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: nzbget
      version: 12.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    env:
      TZ: "America/New_York"
      NZBGET_USER: ${NZBGET_USER}
      NZBGET_PASS: ${NZBGET_PASSWORD}
    podSecurityContext:
      supplementalGroups:
        - 100
      fsGroup: 100
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/nzbget/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "nzbget.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NFS_SERVER}
            path: /volume1/Lab/config/nzbget
        mountPath: /config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NFS_SERVER}
            path: /volume1/Media
        mountPath: /media
    additionalContainers:
      vpn:
        name: vpn
        image: qmcgaw/gluetun:v3.32.0
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
          - name: OPENVPN_USER
            valueFrom:
              secretKeyRef:
                name: vpn-auth-secret
                key: username
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vpn-auth-secret
                key: password
          - name: REGION
            valueFrom:
              secretKeyRef:
                name: vpn-auth-secret
                key: region
          - name: FIREWALL # TODO
            value: "off"
          - name: OPENVPN_IPV6
            value: "off"
          - name: PIA_ENCRYPTION
            value: strong
          - name: PROTOCOL
            value: tcp
          - name: TZ
            value: "America/New_York"
          - name: PORT_FORWARDING
            value: "on"
          - name: HTTPPROXY
            value: "off"
          - name: SHADOWSOCKS
            value: "off"
          - name: FIREWALL_DEBUG
            value: "off"
        livenessProbe:
          exec:
            command:
              - ping
              - -W3
              - -c1
              - -q
              - -s8
              - 1.1.1.1
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 2
