---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: nzbget
      version: 12.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    env:
      TZ: "America/New_York"
    podSecurityContext:
      supplementalGroups:
        - 100
      fsGroup: 100
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/nzbget/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "nzbget.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: nzbget-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NFS_SERVER}
            path: /volume1/Media
        mountPath: /media
