---
- name: configure split dns
  template:
    src: 99-k8s-gateway-forward.conf.j2
    dest: /etc/dnsmasq.d/99-k8s-gateway-forward.conf
    mode: 0644

- name: run pihole tasks
  include_role:
    name: r_pufky.pihole
