---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: sonarr
  components:
    - ../../../../components/volsync
  path: ./cluster/apps/media/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  postBuild:
    substitute:
      APP: sonarr
      VOLSYNC_CAPACITY: 5Gi
  wait: false
  interval: 1h
  retryInterval: 1m
  timeout: 15m
