---
# https://docs.cilium.io/en/latest/network/l2-announcements
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
  namespace: kube-system
spec:
  loadBalancerIPs: true
  interfaces:
    # - ^enx[a-b0-9]+
    - "^enp.*"
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
