---
# https://docs.cilium.io/en/latest/network/l2-announcements
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  loadBalancerIPs: true
  interfaces:
    - ^enx[a-b0-9]+
    - enp2s0
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
