---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-pool
  namespace: kube-system
spec:
  # cidrs:
  #   - cidr: 192.168.42.1/24
  allowFirstLastIPs: "Yes"
  blocks:
    - start: 192.168.42.50
      stop: 192.168.42.99
