---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: home-system
spec:
  chart:
    spec:
      chart: open-webui
      version: 5.26.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  interval: 30m
  values:
    ollama:
      enabled: false
    ingress:
      enabled: true
      class: internal
      host: "ai.${SECRET_DOMAIN}"
      tls: true
    persistence:
      enabled: true
      storageClass: synology-csi-retain
