---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  upgrade:
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      sonarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.16.2946@sha256:22651c750eedb091f6d76ade95dbecae0eeafe2b55432c3b8d8b042e8745f344
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 8989
                  initialDelaySeconds: 45
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 512Mi
            env:
              - name: TZ
                value: America/New_York
              - name: SONARR__APP__INSTANCENAME
                value: Sonarr
              - name: SONARR__SERVER__PORT
                value: *port
              - name: SONARR__LOG__LEVEL
                value: info
              - name: SONARR__LOG__DBENABLED
                value: "False"
              - name: SONARR__AUTH__REQUIRED
                value: DisabledForLocalAddress
              - name: SONARR__AUTH__METHOD
                value: External
              - name: SONARR__AUTH__APIKEY
                valueFrom:
                  secretKeyRef:
                    name: sonarr-secret
                    key: api_key

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]

    service:
      app:
        controller: sonarr
        ports:
          http:
            port: *port

    ingress:
      app:
        className: "internal"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "filmstrip"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</body>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/sonarr/nord.css"></body>';
            sub_filter_once on;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: sonarr
      media:
        type: nfs
        server: nas-2.lan
        path: /volume1/Media
        globalMounts:
          - path: /media
