apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: media
stringData:
    db_host: ENC[AES256_GCM,data:sEQ5RNR5PLc=,iv:dp2BLIV/DIA60gtU0ekqK+it5uIQL0H1IIja/tIoM+s=,tag:++yrfzL9cRHlrBdXXm/dhA==,type:str]
    db_port: ENC[AES256_GCM,data:Q+RTHQ==,iv:gSxqnz7HgE6Ittd3HdWJDIrOKuSfw8K8VCSFH31u76c=,tag:+i9VoPWYVaaDFj5elvPBLA==,type:str]
    db_user: ENC[AES256_GCM,data:SkTlsIyz,iv:MSheQz2AuClMQ4ZHsaCRRgBYSRVLHq3SEpavRL5eHQI=,tag:XXbbvL9ergNzLIDRjodJzQ==,type:str]
    db_pass: ENC[AES256_GCM,data:TQgDHdVYW7dUgvikbe/CIfaNLiowmVa5bk4BWmOmxD8dDQ80HOo7EzgJO1I2seZFlIk=,iv:qUglAU0R598EUFuNzwG+shMzeiDQdu77SO+PTJsn9OY=,tag:W1XQ1oUdde6G66hcdw1frA==,type:str]
    db_main: ENC[AES256_GCM,data:Gb6lOAtw,iv:ug7MDX8qjwC7ozh5I16P3S1WRZPGKaSwY+tZ86cGCfE=,tag:1zfsWa3zKu4eSRaxJHwpIw==,type:str]
    db_logs: ENC[AES256_GCM,data:pDzOxIsV,iv:QRSbkizaO/vcupjJ5JdHkcjaznwDkTRWIfPXHagz6p0=,tag:Zdagoy1MYZLZhkXs6jsXHg==,type:str]
    api_key: ENC[AES256_GCM,data:xdStU6QDOKsM8uDIvirHrtuSFOI5TGOLsw==,iv:bapxZcWMbBM/F1lE4oL2I6NN1REQnJwCWf92lUrWzIc=,tag:JXyrxzE6CNjAsYaCY+apUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNzI0K2RuNWl1TS9tOFNW
            UHpINXl0ZDh5eUZ6YnhJZTdUMUtsN0xhYldNClI0RjJHTmpFenJjN3lqOVhDcC9E
            SC9xaEFyYTBGVVdPT2w3b2F2enlqUHMKLS0tIHJUemF4RUYvYVRGVXhLZUpveHNP
            N1pSSTF2SHlWOHNBc0lORnpzbXBpU0EKeKlqTrPnl764QPcP5ay4nW8M1T2UMJLu
            UgY7hIVE0h0Me9ObdNG5uaoDvrJHDniy0zbUdGcyCyB/Vvi4GpqLOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-19T19:11:07Z"
    mac: ENC[AES256_GCM,data:pMc+Xd+9DdhaKyKclZ45ybSrp86+7yDDeUfXJBDMNB7AWhT1QGE/Sd3LeoldiEOqkP3TXjm8f4PniExGY3GUYbZKVcLnWIM7wzrE7BqEXA3pSKpDJz80SMMnuH+jv/ZiMoKstyLsptcoTgTnNT594c8/D1xNNce3kDxVtiBGv8g=,iv:fziq1einWxsyBklGmIJptou/7cnXhSvAoTLCcBaCvgw=,tag:L2Q5Ba3UwAzvCOUyUBN/CA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
