---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-secret
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: external-dns-secret
  data:
    - secretKey: api-token
      remoteRef:
        key: cloudflare
        property: api-token
