---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homebridge
  namespace: flux-system
spec:
  path: ./cluster/apps/default/homebridge/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  interval: 1h
  retryInterval: 1m
  timeout: 15m
