---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token-secret
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: github-webhook-token-secret
  data:
    - secretKey: token
      remoteRef:
        key: github-webhook
        property: token
