apiVersion: v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: metallb-config-map
data:
    config: ENC[AES256_GCM,data:U05iNpAAATeq7LBfmJYGPPaHbLTKL176y8hy6z4TAtkwhDQENFWjf547Ov2tyg1YcrEOe2wvFvDrPS/mdsgHbXyGeLE3B2/UUrK4JdJcZpzgfNm99RgbzG45eEyiVsz8,iv:+e3bNhwRgw77ndjUY3XArDYETu+gHsb+jLqda0Ze59E=,tag:qN2upFUFV22jTyoPaR4+fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YnFueldhNGRRbCtXOGdq
            M1R2RHVMbGtPODByUTlqQTMwell1VU5vdUU4CjhyWlhRd1UxbDBKRVUzT1lGVVhQ
            dk9DU0dlL04vQ1RUZjBuTTZiRkoyUncKLS0tIGlqQ0dxTFd6ckQzaUttQzBUQkR5
            dCtQRmVaQ002NmFTclRNSVNFM3ZSbUUKHas/iGPErR3l8Se7FW5+GQLhXMOUthcn
            Am4/4c7Sg5/m28e9ew3nTjAEZWjXqtNP2sH4YW/pnKos6rqPieBgDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-31T21:35:51Z"
    mac: ENC[AES256_GCM,data:Bb8ynz/qOXBDPdf5iMuuo0N8B4Hawya3QlFEW/KfsXacyN/bQf6tWr1PeKuj/SCf5RoD3rMI+haj9lSPO7boyPXfUtZWpjBS+gjTD4AiSHB91sYpWoUD9gpjTLSSvHAqmFXqZncEzpKVSBYtOnnpGMWMSNDabn+9HVVB6Sw8r/g=,iv:2tD0Q4kxxqlLVloko6din+xfzw2MfYh2aKS6F6quCdw=,tag:wMRykyYdSXZ1kF5jBFFKUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
