---
k3s_control_node: true

k3s_server_manifests_templates:
  - kube-vip-daemonset.yaml.j2

k3s_server_manifests_urls:
  - url: "https://kube-vip.io/manifests/rbac.yaml"
    filename: "kube-vip-rbac.yaml"

k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    # kube-vip
    - "{{ k3s_registration_address }}"
  docker: false
  disable:
    - traefik
    - servicelb
    - local-storage
  # Network CIDR to use for pod IPs
  cluster-cidr: "10.42.0.0/16"
  # Network CIDR to use for service IPs
  service-cidr: "10.43.0.0/16"
  write-kubeconfig-mode: "644"
  # Required to monitor component with kube-prometheus-stack
  etcd-expose-metrics: true
  kubelet-arg:
    # Allow pods to be rescheduled quicker in the case of a node failure
    # https://github.com/k3s-io/k3s/issues/1264
    - "node-status-update-frequency=4s"
  kube-controller-manager-arg:
    # Required to monitor component with kube-prometheus-stack
    - "bind-address=0.0.0.0"
    # Allow pods to be rescheduled quicker in the case of a node failure
    # https://github.com/k3s-io/k3s/issues/1264
    - "node-monitor-period=4s"
    - "node-monitor-grace-period=16s"
    - "pod-eviction-timeout=20s"
  kube-proxy-arg:
    # Required to monitor component with kube-prometheus-stack
    - "metrics-bind-address=0.0.0.0"
  kube-scheduler-arg:
    # Required to monitor component with kube-prometheus-stack
    - "bind-address=0.0.0.0"
  kube-apiserver-arg:
    # Allow pods to be rescheduled quicker in the case of a node failure
    # https://github.com/k3s-io/k3s/issues/1264
    - "default-not-ready-toleration-seconds=20"
    - "default-unreachable-toleration-seconds=20"
