---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: promtail
      version: 6.17.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  values:
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi

    # Tolerations to run on control plane nodes
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists

    # Monitoring
    serviceMonitor:
      enabled: true
