---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: main
          image: ghcr.io/onedr0p/home-assistant:2024.4.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/New_York
            - name: HASS_HTTP_TRUSTED_PROXY_1
              value: 192.168.42.0/24
            - name: HASS_HTTP_TRUSTED_PROXY_2
              value: 10.244.0.0/16
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: logs
              mountPath: /config/logs
            - name: tts
              mountPath: /config/tts
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-home-assistant
        - name: logs
          emptyDir: {}
        - name: tts
          emptyDir: {}
