# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-system
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities: { drop: ["ALL"] }
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: main
          image: ghcr.io/onedr0p/home-assistant:2024.8.0@sha256:dfbd75acb4acb454d40c5461f653f2c0c9b356d5eafb0e276bf53f8595a1b545
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/New_York
            - name: HASS_HTTP_TRUSTED_PROXY_1
              value: 192.168.0.0/16
            - name: HASS_HTTP_TRUSTED_PROXY_2
              value: 10.244.0.0/16
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: logs
              mountPath: /config/logs
            - name: tts
              mountPath: /config/tts
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-home-assistant
        - name: logs
          emptyDir: {}
        - name: tts
          emptyDir: {}
