---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      restartPolicy: Always
      containers:
        - name: main
          image: ghcr.io/home-assistant/home-assistant:2024.2.3
          imagePullPolicy: IfNotPresent
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-home-assistant
