server_name: ENC[AES256_GCM,data:iffENg==,iv:sVRgcJcaZqif3CSpKMAJxfS/M5xOz2gcJKDk8aBHCjg=,tag:cFpSJtyuEpoo0pthW94o3w==,type:str]
world_name: ENC[AES256_GCM,data:B/y0+A==,iv:B3JpLuQxQUioIY3hsGMqdhvrIkZpakxx5hTPXMfRkZ8=,tag:R/ibvWVwZSU3QwBKUCh0tA==,type:str]
server_pass: ENC[AES256_GCM,data:B1TqOEY=,iv:B9YjNW8eyZf2YA+JqeayGGSV5ICrc952kqgzUnFLwS0=,tag:BPL8lZ9b2OrkYe8gXsyAOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUEF1c09GVTN4aVVOTyto
            eWtzeFlQb3RQblR1emNRMGVHZDRDbEdkZ2xVClZCbGxoM2VmUlN0TXExS0lmR1cr
            VmFoaWRod0dtVXNYZy9LWFhXTHJOS0kKLS0tIDdCdThYLzQ0Z0hMbk5RR0Y5RHZ1
            SEgwWTRMT2FlZytvd3dlazdiQXphTTAK8lghu21/ZdYZ4jlmAI3mVASMBIKIlnoK
            IHOD5K9Ag8+0mzFXMzIdDnNXKt5Uf9ftPTToGKO/V+jRElkfvITxhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-11T16:34:16Z"
    mac: ENC[AES256_GCM,data:3ONpjqt0JoiNPMfd2NsBdCR8NPpHRYdd1f2aRcyGP7JMSOgOFNrXftne+c6nQbVixHZkWdny3yjigUKkfY3Ukv2/1A+HHjM58Qs/RaQ1MnwCNKL8khEYu6I37FWRptAvFDYRtgcB6MIXps/GbCHEnarFqGqGe/dCG9xzoL/UODg=,iv:h+puFOymuI1aG46P4wFWIPfu9/wB68+Tm6Tx/va0ln8=,tag:1+/jnwZkcbcTn1Vj/O4e8A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
