---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "true"
data:
  plex-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Plex
        type: yesoreyeram-infinity-datasource
        uid: plex
        access: proxy
        jsonData:
          auth_method: apiKey
          apiKeyKey: X-Plex-Token
          apiKeyType: query
          allowedHosts:
            - http://plex.media.svc.cluster.local:32400
        secureJsonData:
          apiKeyValue: $PLEX_TOKEN
