apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:I90j5Fk=,iv:ejd8iAZGFHBi0raL1I+ZuPBJF2TWFCNXLRcUGBrwx+M=,tag:HnMV5HwNL9+UBHLWEkyhTQ==,type:str]
    admin-password: ENC[AES256_GCM,data:ig/nA/ZxzL6fN9IUgY9YIiUvHuK67yaFJlKaPWm1RHV1AOa8D8LXXACTQAUekJNYS1g=,iv:no2csRdqRHVH8+gYWr0T6ynU0xOI89Q/IDW9OAq2BpM=,tag:E0KuiMWzTNPnatFMZdeXOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSjk0TUdRdWJHYXZ6TEZM
            eGtKU0wvTk5UR0o0NGxSdlVZV3R2cklXTWpjCmNuYTVDVkhKd0NHUndSRTNzSEo4
            OC9VaTk5Y0VTcEdyaWRvd3VZelk0K2sKLS0tIEtsNDh2MG1IckVLMHFJL1gyOXcy
            eU8xS3JjOURmQWZ1YWRYRXV6dC83d1UK1QMoOdErc10V7OEDmemTWcrzA1IZfFGg
            YbIXv/zzrcIbc3/Q6GeNjyrO7Ca2I4MwAMX7N2/AcKOnHWkrhz5okQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-19T03:07:03Z"
    mac: ENC[AES256_GCM,data:4C6hNUlRGlkixQGuYFtIDzRS8kzUe7GHjq0qnQwjeXZrRiP4cHDgGam1ZdF4im4tmzj+5V3jDOeJdQRtzGbwYgJwgq+tMLezsp6Svemus3rp9sVJaupRFOT5f3bN4qaHH5FWM86WzZw6uMkPd4E0zBxk1GKKCh90l4FxBSmtVWQ=,iv:3u75F1xPH4xdpFUR4vw8eOaKXEznF357xsG9jih9fw0=,tag:r0ZXJYSLw8AyD66NNZ56Fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
