---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tautulli-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "true"
data:
  tautulli-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Tautulli
        type: yesoreyeram-infinity-datasource
        uid: tautulli
        access: proxy
        jsonData:
          auth_method: apiKey
          apiKeyKey: apikey
          apiKeyType: query
          allowedHosts:
            - http://tautulli.media.svc.cluster.local:8181
        secureJsonData:
          apiKeyValue: $TAUTULLI_API_KEY
