---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-operator
  targetNamespace: external-secrets
  commonMetadata:
    labels:
      app.kubernetes.io/name: onepassword-connect
  path: ./cluster/apps/external-secrets/onepassword-connect/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 1h
  timeout: 5m
