---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mangawatch
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: deployment
        pod:
          imagePullSecrets:
            - name: ghcr-login-secret
        containers:
          main:
            image:
              repository: ghcr.io/davidharrigan/manga-scraper
              tag: 0.10.0
            env:
              - name: MANGA_SCRAPER_LOGGING_LEVEL
                value: "info"
              - name: MANGA_SCRAPER_DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: mangawatch-secret
                    key: db_url
              - name: MANGA_SCRAPER_SLACK_ENABLED
                valueFrom:
                  secretKeyRef:
                    name: mangawatch-secret
                    key: slack_enabled
              - name: MANGA_SCRAPER_SLACK_APP_ID
                valueFrom:
                  secretKeyRef:
                    name: mangawatch-secret
                    key: slack_app_id
              - name: MANGA_SCRAPER_SLACK_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: mangawatch-secret
                    key: slack_client_id
              - name: MANGA_SCRAPER_SLACK_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: mangawatch-secret
                    key: slack_client_secret
              - name: MANGA_SCRAPER_SLACK_REDIRECT_URL
                valueFrom:
                  secretKeyRef:
                    name: mangawatch-secret
                    key: slack_redirect_url
              - name: MANGA_SCRAPER_SLACK_APP_INSTALL_REDIRECT_URL
                valueFrom:
                  secretKeyRef:
                    name: mangawatch-secret
                    key: slack_app_install_redirect_url
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 500Mi

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "manga.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
