{
 "title": "iDRAC",
 "tags": [ "dashlinks" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "type",
    "query": "label_values(up{device_type=\"dell\"},device_type)"
   },
   {
    "name": "node",
    "query": "label_values(up{device_type=\"$type\"}, hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Server basic information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(processorDeviceIndex{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(memoryDeviceSize{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "systemPowerState{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "DISK ISSUES",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "physicalDiskComponentStatus{hostname=\"$node\"} == 4"
    }
   ]
  },
  {
   "title": "CONTROLLER BATTERY",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "systemStateBatteryStatusCombined{hostname=\"$node\"} != 3"
    }
   ]
  },
  {
   "title": "PS1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "powerSupplyStatus{hostname=\"$node\", powerSupplyIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "amperageProbeReading{hostname=\"$node\"} > 20"
    }
   ]
  },
  {
   "title": "CORES",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(processorDeviceCoreCount{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(physicalDiskCapacityInMB{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "PS2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "powerSupplyStatus{hostname=\"$node\", powerSupplyIndex=\"2\"}"
    }
   ]
  },
  { "title": "Server temperature sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Server temperature sensors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(temperatureProbeReading{hostname=\"$node\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{hostname=\"$node\"})",
     "legendFormat": "{{temperatureProbeLocationName}}"
    },
    {}
   ]
  },
  { "title": "Server hard disk information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(physicalDiskCapacityInMB{hostname=\"$node\"}) + on (physicalDiskNumber) group_left(physicalDiskDisplayName) (physicalDiskDisplayName{hostname=\"$node\"}) + on (physicalDiskNumber) group_left(physicalDiskProductID) (physicalDiskProductID{hostname=\"$node\"})  + on (physicalDiskNumber) group_left(physicalDiskSerialNo) (physicalDiskSerialNo{hostname=\"$node\"}) "
    },
    {
     "expr": "physicalDiskComponentStatus{hostname=\"$node\"}"
    }
   ]
  }
 ]
}