---
# TODO: vip for control plane

# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_version: "v1.24.7+k3s1"
k3s_become: true
k3s_debug: false
k3s_etcd_datastore: true
k3s_install_hard_links: true

# k3s_use_unsupported_config: true
