---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      version: 2.2.1
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
  values:
    connect:
      create: true
      replicas: 1
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
      api:
        serviceMonitor:
          enabled: true
          interval: 30s
    operator:
      create: false
