---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace
  - gotk-components.yaml
  - gotk-sync.yaml
  - charts
  # TODO: move these out
  # - monitoring
  # - dashboard
patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        decryption:
          provider: sops
          secretRef:
            name: sops-age
    target:
      version: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      name: flux-system
