---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: cluster-secrets
  data:
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: cluster-secrets/domain
    - secretKey: SECRET_ACME_EMAIL
      remoteRef:
        key: cluster-secrets/acme_email
    - secretKey: SECRET_CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: cloudflared/TUNNEL_ID
