---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-volsync-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: volsync
  targetNamespace: media
  path: ./cluster/apps/media/volsync-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
