---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-system
spec:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "mqtt.${SECRET_DOMAIN}"
    io.cilium/lb-ipam-ips: 192.168.42.52
  selector:
    app: mosquitto
  ports:
    - name: mqtts
      protocol: TCP
      port: 1883
      targetPort: 1883
