---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 15Gi
              storageClass: mayastor-1
              globalMounts:
                - path: /config
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 65539
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.32.2.7100-248a2daf0@sha256:24b39030607af2ac007d48d508acdb136a925c1c66c2b495e18989eb857082ed
            resources:
              requests:
                cpu: 100m
                memory: 1500Mi
              limits:
                memory: 3000Mi

    service:
      main:
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: nas-2.lan
            path: /volume1/Media
        mountPath: /media
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
