ansible_user: ENC[AES256_GCM,data:KHY/O1A=,iv:slhEd+MeBNhAO5nrXE3eLiACuV3jHyLVdmu9CenxiEo=,tag:Rs7vTR0rwZHiSK3KgSS8kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZWtuTGlJVWF4Zll0ektU
            SXpxRFJvRithU3lDQTJzNktDQ3dieml1d2xZCkFndEp5YlcySnNNM1pBUlFKWFo0
            QTRiRWl5cVpWUGRhT3ZNQWNkeHRjRWsKLS0tIFFqSFJpVDBHbkYwcVNYcXlab21u
            SlJ4ZUtvT25HOGhyNFVlZk9wM0xVc3MKKFQi8pgnGsjmwihwx24Cm78KBH9jbILZ
            Jkr3ny3N7LvHiQteOKn930jDz5mtWj0dKAlAhd4GWVkulyW4XfjhVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-01T17:46:55Z"
    mac: ENC[AES256_GCM,data:ShTEB/a4EF8q6cPB+kULCgAjD56gubTl724eanw6Lzdb0sPdfnmydsDFn8VUobqhLKK1lg+XdhfYHH2rq6Az8kBNtf17jAtndMR/TgY6VU+q0jFwEVllt0ITy+sLWqK3ry1gR4BjKLaOG8nhIvZR7V09iwBc7Bqc1eQu3buVC+A=,iv:8Fpa3wpdFSf+8RHh1Y5AdogxldKyWVNa598dtY3o8mk=,tag:fwusMHDjh1dVbsMwE6I2gQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
