apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    SETTINGS_PLACEHOLDER: ENC[AES256_GCM,data:j4kJezAsyVxZDGdtyxA=,iv:djLVV20Zzc4rv3KNZXHivTlx5LOtKgVlsB9gtpwu8pE=,tag:oSGlY/8nP3HgVk7F86I06Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdUFLM1ZoOUFhZTRWMzJm
            ODQxazZiMjBnL3ZSbi9TUk9LNmdOQkVqK3drCm54ZmI3M2RSRUVjYUJTSy9aa0dP
            cGU5NmNSNTJxKzA5amIxTE1Zc2Yrd3MKLS0tIGg4NlRBdk9aMVBNakN4OUpMaWs0
            TFFSUHFYRjBKckVqejEvOFkyNVFvRkEKwrUj7bb1x5tLukRKKY8AsUXXi8XeFMfV
            kTibRvnJdx9BUhC2tzckqWwGKIKQFzFneEgYyLnAjiIrgRN0Xc/39g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T13:35:06Z"
    mac: ENC[AES256_GCM,data:ZlcZxWF2Gyfqf2fw6Ig7c7itIaEia3BFlNu26AoOuN9mbuZmHGEHMm8wuChrQPEL005OYGfA4laGoaHYx/CTzA2cP9ngmi7uRP3AxRIJA9uHU4oUhdJKFZQOays36Zw01VfF7Dx781Yy47EZMk/+E0SOrRESHKXMAVXK6pdvyWM=,iv:HiYxnQjLlsb3Y4KGnzSzWaMld1kmulGOEPxMVR2HJj4=,tag:eGqJoriaHRLx2Y6SFwNLaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
