---
- name: Install Postgres
  become: true
  gather_facts: true
  any_errors_fatal: true
  hosts:
    - db
  tasks:
    - name: Install Postgres
      ansible.builtin.include_role:
        name: geerlingguy.postgresql
        public: true
      vars:
        postgresql_python_library: python3-psycopg2
