---
- name: configure dns servers
  become: true
  gather_facts: true
  any_errors_fatal: true
  hosts:
    - dns
  pre_tasks:
    - name: install packages
      package:
        name: sqlite3
        state: present
  roles:
    - pihole
