---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h
  path: ./cluster/apps/kube-system/metrics-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  targetNamespace: kube-system
  wait: false
