---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: home-ops
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          namespace: external-secrets
          key: token
