---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homebridge
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      homebridge:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 3Gi
              storageClass: synology-csi-retain
              globalMounts:
                - path: /homebridge
        containers:
          app:
            image:
              repository: oznu/homebridge
              tag: "2023-01-08"
            env:
              TZ: America/New_York
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                cpu: 500m
                memory: 500Mi

    service:
      app:
        controller: homebridge
        ports:
          http:
            port: 8581

    ingress:
      app:
        className: internal
        hosts:
          - host: &host "homebridge.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
