---
name: "Flux Diff"

on:
  pull_request:
    branches: ["main"]
    paths: ["cluster/**.yaml"]

jobs:
  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        path: ["cluster"]
        resource: ["helmrelease", "kustomization"]
    steps:
      - name: Configure Github access # flux-local/action needs to accept a token
        run: |
          /usr/bin/git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github.com/davidharrigan/home-ops".insteadOf https://github.com/davidharrigan/home-ops
      - name: Diff Resources
        uses: allenporter/flux-local/action/diff@3.1.1
        id: diff
        with:
          live-branch: main
          sources: home-cluster
          path: "${{ matrix.path }}"
          resource: "${{ matrix.resource }}"

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add comment
        uses: mshick/add-pr-comment@7c0890544fb33b0bdd2e59467fbacb62e028a096 # v2.8.1
        with:
          repo-token: "${{ secrets.ACCESS_TOKEN }}"
          message-id: "${{ github.event.pull_request.number }}/${{ matrix.path }}/${{ matrix.resource }}"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
