---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tautulli-exporter-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: tautulli-exporter-secret
  data:
    - secretKey: TAUTULLI_API_KEY
      remoteRef:
        key: tautulli
        property: api_key
