---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tautulli-exporter
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      tautulli-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/scabraha/tautulli-exporter
              tag: 2.1.3@sha256:92a54157f531f2f5c5b0a21f9671189c8eb34ad78611a99bff0fe7737b4fed54
            env:
              TAUTULLI_URL: http://tautulli.media.svc.cluster.local:8181
              EXPORTER_PORT: &port 9487
              LIBRARY_SIZE_ENABLED: "true"
              LOG_FORMAT: json
            envFrom:
              - secretRef:
                  name: tautulli-exporter-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /metrics
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: tautulli-exporter
        ports:
          metrics:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 30s
