---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: transmission
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    initContainers: {}

    image:
      repository: ghcr.io/k8s-at-home/transmission
      tag: v3.00

    env:
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_DOWNLOAD_DIR: /media/Downloads
      TRANSMISSION_INCOMPLETE_DIR: /media/Downloads/temp
      TZ: "America/New_York"
      TRANSMISSION_RPC_USERNAME: admin
      TRANSMISSION_RPC_PASSWORD: admin
      WAIT_FOR_VPN: "true"

    podSecurityContext:
      fsGroup: 0
      runAsUser: 0
      runAsGroup: 0
      fsGroupChangePolicy: "Always"

    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NFS_SERVER}
            path: /volume1/Lab/config/transmission
        mountPath: /config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NFS_SERVER}
            path: /volume1/Media
        mountPath: /media
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          # Custom themes provided by https://github.com/gilbN/theme.park
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_hide_header "x-webkit-csp";
            proxy_hide_header "content-security-policy";
            proxy_hide_header "X-Frame-Options";
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/transmission/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: "transmission.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    addons:
      vpn:
        enabled: true
        type: openvpn
        openvpn:
          authSecret: ovpn-auth-secret
        configFileSecret: ovpn-config-secret
        scripts:
          up: |-
            #!/bin/bash
            /etc/openvpn/up.sh
            echo "connected" > /shared/vpnstatus
          down: |-
            #!/bin/bash
            /etc/openvpn/down.sh
            echo "disconnected" > /shared/vpnstatus
